# ============================================================================
# CompilerFlags.cmake
# ============================================================================
# Defines strict, production-ready compilation flags for MSVC (Visual Studio).
# Enforces C++20, high warnings, and separates Debug/Release optimizations.
# ============================================================================

# Enforce C++20 globally
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

# --------------------------------------------------------------------------
# MSVC Specific Configuration
# --------------------------------------------------------------------------
if(MSVC)
    
    # ------------------------------------------------------------------
    # Common Flags (Applied to Debug AND Release)
    # ------------------------------------------------------------------
    add_compile_options(
        /W4               # High warning level (enables most warnings)
        /WX               # Treat all warnings as errors
        /utf-8            # Set source and execution character sets to UTF-8
        /MP               # Multi-processor compilation (drastically speeds up builds)
        /permissive-      # Strict standard conformance
        /Zc:__cplusplus   # Force the __cplusplus macro to report the correct standard
        /EHsc             # Enable standard C++ exception handling
        /GR               # Enable Run-Time Type Information (RTTI)
    )

    # ------------------------------------------------------------------
    # Global Definitions
    # ------------------------------------------------------------------
    # Silence noisy warnings generated by Adobe SDK and ONNX Runtime headers
    add_compile_definitions(
        _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS
        _SILENCE_CXX20_ADAPT_TYPE_TRAITS_DEPRECATION_WARNING
        _CRT_SECURE_NO_WARNINGS
        NOMINMAX           # Prevent Windows.h from polluting global namespace with min/max
    )

    # ------------------------------------------------------------------
    # Debug Configuration
    # ------------------------------------------------------------------
    add_compile_options(
        $<$<CONFIG:Debug>:/Zi>       # Generate full debugging information (PDB)
        $<$<CONFIG:Debug>:/Od>       # Disable optimizations (fastest compile, easiest debug)
        $<$<CONFIG:Debug>:/RTCc>     # Enable run-time checks for type conversions
    )

    # ------------------------------------------------------------------
    # Release Configuration
    # ------------------------------------------------------------------
    add_compile_options(
        $<$<CONFIG:Release>:/O2>         # Maximize speed (standard for production)
        $<$<CONFIG:Release>:/DNDEBUG>    # Disable assertions and debug logic
        $<$<CONFIG:Release>:/GL>         # Enable whole program optimization
        $<$<CONFIG:Release>:/arch:AVX2>  # Enable Advanced Vector Extensions 2 for math/Array ops
    )

    # Release Linker Flags (Must match /GL)
    add_link_options(
        $<$<CONFIG:Release>:/LTCG>       # Link-time code generation
        $<$<CONFIG:Release>:/OPT:REF>    # Eliminate unused functions and data
        $<$<CONFIG:Release>:/OPT:ICF>    # Enable COMDAT folding
    )

else()
    message(WARNING "CompilerFlags.cmake is strictly configured for MSVC (Windows x64). Non-MSVC compilers are not currently supported by CineGrade AI.")
endif()
